language: node_js
node_js:
- 0.10
services:
- redis-server
before_install:
- "sed -i \"s/\\\"version\\\": \\\"\\([0-9]\\).\\([0-9]\\).0-dev/\\\"version\\\": \\\"\\1.\\2.$TRAVIS_BUILD_NUMBER-dev/\" package.json"
before_script:
- mysql -e 'create database saram_test;'
after_success:
- rm -rf saram-core node_modules saram.log
notifications:
  email: false
deploy:
  provider: npm
  email: shlee322@gmail.com
  skip_cleanup: true
  api_key:
    secure: JW9f2JJtRUNyBL0w2wNL2pL05r7sKatNGJiAsQcAhBi0epWO6H5ETpc8cNVJJu5bOYJxO8mDwtG9YB8cRq8d0B40imZgyH9yg287raSI+8hpdJh0BecypSPbwh35nWUKJVbTh/KE1iaLhkYKm5dhHthKnPZjdM2/0TUJ/Z558X8=
